/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Program: Sistem Informasi Kebudayaan
 * NPM: 2410010589
 * Mata Kuliah: Pemrograman Berbasis Objek
 * 
 * File: frameKebudayaan.java
 * Deskripsi: Frame untuk input dan menampilkan Data Kebudayaan dalam bentuk tabel.
 *            User bisa menambah data kebudayaan baru melalui form ini.
 *            Mirip dengan frameMataKuliah dalam project KHS.
 */
package Form;

import javax.swing.table.DefaultTableModel;
import Kebudayaan.DataKebudayaan;

/**
 * Class frameKebudayaan
 * @author NPM: 2410010589
 * 
 * Deskripsi:
 * Frame ini digunakan untuk input data kebudayaan dan menampilkan dalam tabel.
 * User dapat:
 * 1. Input ID, Nama, Deskripsi, dan Kategori kebudayaan
 * 2. Klik tombol TAMBAH untuk menambahkan data ke tabel
 * 3. Melihat semua data kebudayaan dalam table view
 */
public class frameKebudayaan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameKebudayaan.class.getName());

    // Deklarasi object DataKebudayaan untuk menyimpan data
    DataKebudayaan obj;
    
    /**
     * Constructor - Membuat dan inisialisasi form
     */
    public frameKebudayaan() {
        initComponents();
        // Membuat instance baru dari DataKebudayaan
        obj = new DataKebudayaan();
        
        // Memposisikan window di tengah screen
        this.setLocationRelativeTo(null);
        
        // Memanggil method tampilDataKebudayaan untuk display tabel kosong
        tampilDataKebudayaan();
    }

    private void tampilDataKebudayaan() {
        // Membuat instance DefaultTableModel untuk manage tabel
        DefaultTableModel modelKolom = new DefaultTableModel();
        
        // Menambahkan column header ke table model
        modelKolom.addColumn("ID Kebudayaan");      // Kolom 1
        modelKolom.addColumn("Nama Kebudayaan");    // Kolom 2
        modelKolom.addColumn("Deskripsi");          // Kolom 3
        modelKolom.addColumn("Kategori");           // Kolom 4
        
        // Loop untuk menambahkan setiap baris data dari ArrayList
        for (int i = 0; i < obj.listDataId().size(); i++) {
            // Membuat array untuk satu baris data
            Object[] barisData = {
                obj.listDataId().get(i),           // ID dari index i
                obj.listDataNama().get(i),         // Nama dari index i
                obj.listDataDeskripsi().get(i),    // Deskripsi dari index i
                obj.listDataKategori().get(i)      // Kategori dari index i
            };
            
            // Menambahkan baris ke table model
            modelKolom.addRow(barisData);
        }
        
        // Set table model ke JTable untuk menampilkan data
        tabelKebudayaan.setModel(modelKolom);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdKebudayaan = new javax.swing.JTextField();
        txtNamaKebudayaan = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        txtKategori = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKebudayaan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Form Data kebudayaan");

        jLabel2.setText("ID Kebudyaan");

        jLabel3.setText("Nama Kebudyaan");

        jLabel4.setText("Deskripsi");

        jLabel5.setText("Kategori");

        txtIdKebudayaan.addActionListener(this::txtIdKebudayaanActionPerformed);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        tabelKebudayaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Deskripsi", "Kategori"
            }
        ));
        jScrollPane1.setViewportView(tabelKebudayaan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnTambah))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdKebudayaan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaKebudayaan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDeskripsi)
                            .addComponent(txtKategori, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdKebudayaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaKebudayaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKebudayaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKebudayaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKebudayaanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // Mengambil text dari masing-masing text field
        String id = txtIdKebudayaan.getText();
        String nama = txtNamaKebudayaan.getText();
        String deskripsi = txtDeskripsi.getText();
        String kategori = txtKategori.getText();
        
        // Validasi input - cek apakah ada field yang kosong
        if (id.isEmpty() || nama.isEmpty() || deskripsi.isEmpty() || kategori.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Semua field harus diisi!", 
                "Validasi Input", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari method jika ada field kosong
        }
        
        // Menambahkan data ke object DataKebudayaan
        obj.inputIdKebudayaan(id);
        obj.inputNamaKebudayaan(nama);
        obj.inputDeskripsi(deskripsi);
        obj.inputKategori(kategori);
        
        // Refresh tabel untuk menampilkan data baru
        tampilDataKebudayaan();
        
        // Clear semua text field setelah data ditambahkan
        txtIdKebudayaan.setText("");
        txtNamaKebudayaan.setText("");
        txtDeskripsi.setText("");
        txtKategori.setText("");
        
        // Set focus ke field ID untuk input berikutnya
        txtIdKebudayaan.requestFocus();
        
        // Menampilkan message bahwa data berhasil ditambahkan
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Data Kebudayaan berhasil ditambahkan!", 
            "Sukses", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameKebudayaan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKebudayaan;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtIdKebudayaan;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtNamaKebudayaan;
    // End of variables declaration//GEN-END:variables
}
