/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Program: Sistem Informasi Kebudayaan
 * NPM: 2410010589
 * Mata Kuliah: Pemrograman Berbasis Objek
 * 
 * File: frameSitus.java
 * Deskripsi: Frame untuk input dan menampilkan Data Situs/Tempat Sejarah dalam bentuk tabel.
 *            User bisa menambah data situs baru melalui form ini.
 *            Mirip dengan frameMahasiswa dalam project KHS.
 */
package Form;

import javax.swing.table.DefaultTableModel;
import Kebudayaan.Situs;

/**
 * Class frameSitus
 * @author NPM: 2410010589
 * 
 * Deskripsi:
 * Frame ini digunakan untuk input data Situs/Tempat Sejarah dan menampilkan dalam tabel.
 * User dapat:
 * 1. Input ID, Nama, Lokasi, dan Karakterisasi Situs
 * 2. Klik tombol TAMBAH untuk menambahkan data ke tabel
 * 3. Melihat semua data Situs dalam table view
 * 
 * Data yang disimpan berdasarkan Tabel Situs Makam dari jurnal.
 */
public class frameSitus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameSitus.class.getName());

    // Deklarasi object Situs untuk menyimpan data
    Situs obj;
    /**
     * Creates new form frameSitus
     */
    public frameSitus() {
        initComponents();
        // Membuat instance baru dari Situs
        obj = new Situs();
        
        // Memposisikan window di tengah screen
        this.setLocationRelativeTo(null);
        
        // Memanggil method tampilDataSitus untuk display tabel kosong
        tampilDataSitus();
    }
    
    private void tampilDataSitus() {
        // Membuat instance DefaultTableModel untuk manage tabel
        DefaultTableModel modelKolom = new DefaultTableModel();
        
        // Menambahkan column header ke table model
        modelKolom.addColumn("ID Situs");         // Kolom 1
        modelKolom.addColumn("Nama Situs");       // Kolom 2
        modelKolom.addColumn("Lokasi");           // Kolom 3
        modelKolom.addColumn("Karakterisasi");    // Kolom 4
        
        // Loop untuk menambahkan setiap baris data dari ArrayList
        for (int i = 0; i < obj.listDataId().size(); i++) {
            // Membuat array untuk satu baris data
            Object[] barisData = {
                obj.listDataId().get(i),              // ID dari index i
                obj.listDataNama().get(i),            // Nama dari index i
                obj.listDataLokasi().get(i),          // Lokasi dari index i
                obj.listDataKarakterisasi().get(i)    // Karakterisasi dari index i
            };
            
            // Menambahkan baris ke table model
            modelKolom.addRow(barisData);
        }
        
        // Set table model ke JTable untuk menampilkan data
        tabelSitus.setModel(modelKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdSitus = new javax.swing.JTextField();
        txtNamaSitus = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        txtKarakterisasi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelSitus = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Form Data Situs");

        jLabel2.setText("ID Situs");

        jLabel3.setText("Nama Situs");

        jLabel4.setText("Lokasi");

        jLabel5.setText("Karakterisasi");

        txtIdSitus.addActionListener(this::txtIdSitusActionPerformed);

        txtKarakterisasi.addActionListener(this::txtKarakterisasiActionPerformed);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        tabelSitus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Situs", "Nama Situs", "Lokasi", "Karakterisasi"
            }
        ));
        jScrollPane2.setViewportView(tabelSitus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdSitus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnTambah))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNamaSitus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(txtLokasi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtKarakterisasi, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdSitus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaSitus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKarakterisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKarakterisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKarakterisasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKarakterisasiActionPerformed

    private void txtIdSitusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSitusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSitusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // Mengambil text dari masing-masing text field
        String id = txtIdSitus.getText();
        String nama = txtNamaSitus.getText();
        String lokasi = txtLokasi.getText();
        String karakterisasi = txtKarakterisasi.getText();
        
        // Validasi input - cek apakah ada field yang kosong
        if (id.isEmpty() || nama.isEmpty() || lokasi.isEmpty() || karakterisasi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Semua field harus diisi!", 
                "Validasi Input", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari method jika ada field kosong
        }
        
        // Menambahkan data ke object Situs
        obj.inputIdSitus(id);
        obj.inputNamaSitus(nama);
        obj.inputLokasi(lokasi);
        obj.inputKarakterisasi(karakterisasi);
        
        // Refresh tabel untuk menampilkan data baru
        tampilDataSitus();
        
        // Clear semua text field setelah data ditambahkan
        txtIdSitus.setText("");
        txtNamaSitus.setText("");
        txtLokasi.setText("");
        txtKarakterisasi.setText("");
        
        // Set focus ke field ID untuk input berikutnya
        txtIdSitus.requestFocus();
        
        // Menampilkan message bahwa data berhasil ditambahkan
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Data Situs berhasil ditambahkan!", 
            "Sukses", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameSitus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelSitus;
    private javax.swing.JTextField txtIdSitus;
    private javax.swing.JTextField txtKarakterisasi;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNamaSitus;
    // End of variables declaration//GEN-END:variables
}
